Build failed:
CSC : error CS1705: Assembly 'CK.Env.FileSystem' with identity 'CK.Env.FileSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.FileProviders.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.FileProviders.Abstractions' with identity 'Microsoft.Extensions.FileProviders.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' [C:\Dev\CK\CK-Env\Plugins\CK.Env.Plugin.NPM\CK.Env.Plugin.NPM.csproj]